#!/usr/bin/env python3

#Simulator of fair coin toss using random number generator

import random

#State h as HEADS equal to 0
h=0
#State t as TAILS equial to 1
t=1
#Use randint from random module to generate random integer number 0 OR 1
#(will generate 0 OR 1 with 50% probability of both
r=random.randint(0,1)
#create a if-loop with boolean expression h==r,
#as if random generator output is 0 print HEADS
if h==r:
       print('HEADS')
#otherwise print TAILS
else:
       print('TAILS')
